language: go
sudo: false

install:
  - export GO15VENDOREXPERIMENT=1
  - wget https://github.com/Masterminds/glide/releases/download/0.10.2/glide-0.10.2-linux-386.zip -O glide.zip
  - unzip glide.zip
  - export PATH=$PATH:$PWD/linux-386/

go:
  - 1.7
  - tip
